-- MySQL Script generated by MySQL Workbench
-- Sat Jul 18 17:25:48 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema db_biblioteca123
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema db_biblioteca123
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `db_biblioteca123` DEFAULT CHARACTER SET utf8 ;
USE `db_biblioteca123` ;

-- -----------------------------------------------------
-- Table `db_biblioteca123`.`permiso`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`permiso` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `slug` VARCHAR(50) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `usuario` VARCHAR(50) NOT NULL,
  `password` VARCHAR(100) NOT NULL,
  `nombre` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`usurio_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`usurio_rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `estado` TINYINT(1) NOT NULL,
  `rol_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_usurio_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  INDEX `fk_usurio_rol_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_usurio_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_biblioteca123`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_usurio_rol_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_biblioteca123`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`permiso_rol`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`permiso_rol` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `permiso_id` INT NOT NULL,
  `rol_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_permiso_rol_permiso_idx` (`permiso_id` ASC) VISIBLE,
  INDEX `fk_permiso_rol_rol1_idx` (`rol_id` ASC) VISIBLE,
  CONSTRAINT `fk_permiso_rol_permiso`
    FOREIGN KEY (`permiso_id`)
    REFERENCES `db_biblioteca123`.`permiso` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_permiso_rol_rol1`
    FOREIGN KEY (`rol_id`)
    REFERENCES `db_biblioteca123`.`rol` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`libro`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`libro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `titulo` VARCHAR(100) NOT NULL,
  `isbn` VARCHAR(30) NOT NULL,
  `autor` VARCHAR(100) NOT NULL,
  `cantidad` TINYINT(2) NOT NULL,
  `editorial` VARCHAR(50) NULL,
  `foto` VARCHAR(100) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `db_biblioteca123`.`libro_prestamo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `db_biblioteca123`.`libro_prestamo` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fecha_prestamo` DATE NOT NULL,
  `prestadoa_a` VARCHAR(100) NOT NULL,
  `estado` TINYINT(1) NOT NULL,
  `fecha_devolucion` DATE NULL,
  `libro_id` INT NOT NULL,
  `usuario_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_libro_prestamo_libro1_idx` (`libro_id` ASC) VISIBLE,
  INDEX `fk_libro_prestamo_usuario1_idx` (`usuario_id` ASC) VISIBLE,
  CONSTRAINT `fk_libro_prestamo_libro1`
    FOREIGN KEY (`libro_id`)
    REFERENCES `db_biblioteca123`.`libro` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_libro_prestamo_usuario1`
    FOREIGN KEY (`usuario_id`)
    REFERENCES `db_biblioteca123`.`usuario` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
